---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[test_solr]
      - recipe[application_solr]
    attributes:
      application_solr:
        cores:
          packagist:
            schema_xml: https://raw.githubusercontent.com/composer/packagist/master/doc/schema.xml

